---
engine_version: 0.5.0
file_version: 2026-06-26 11:34:52.362535000 Z
resources:
- name: active_storage/attachment
  preferences: {}
  updated_at: 2026-06-18 02:58:55.033703000 +00:00
- name: banner
  preferences:
    display_name: 首页轮播
    columns:
    - display_name: 视频
      reference:
        name: video_attachment
        display_name: Video attachment
        model_name: active_storage/attachment
        reference_type: has_one
        foreign_key: record_id
        primary_key: id
        options: {}
        polymorphic:
        virtual: false
      name: video_attachment
    - display_name: 排序
      name: position
    - display_name: 标题
      name: title
    - display_name: 子标题
      name: subtitle
    - display_name: 跳转链接
      name: redirect_link
    - display_name: 文本位置
      column_type: tag
      format:
        select_options:
        - left
        - right
        - top
        - bottom
      name: text_position
    - display_name: 更新时间
      name: updated_at
    - display_name: 创建时间
      name: created_at
    - reference:
        name: image_pc_attachment
        display_name: Image pc attachment
        model_name: active_storage/attachment
        reference_type: has_one
        foreign_key: record_id
        primary_key: id
        options: {}
        polymorphic:
        virtual: false
      display_name: 图片_PC端
      name: image_pc_attachment
    - reference:
        name: image_mobile_attachment
        display_name: Image mobile attachment
        model_name: active_storage/attachment
        reference_type: has_one
        foreign_key: record_id
        primary_key: id
        options: {}
        polymorphic:
        virtual: false
      display_name: 图片_移动端
      name: image_mobile_attachment
    tabs:
    - visible: false
      name: audits
    - visible: false
      name: notes
  updated_at: 2026-06-18 03:33:00.555009000 +00:00
- name: category
  preferences:
    display_name: 类别列表
    columns:
    - display_name: 上层
      reference:
        name: parent
        display_name: Parent
        model_name: category
        reference_type: belongs_to
        foreign_key: parent_id
        primary_key: id
        options: {}
        polymorphic:
        virtual: false
      name: parent_id
    - display_name: 名称
      name: name
    - display_name: 更新时间
      name: updated_at
    - display_name: 创建时间
      name: created_at
    scopes:
    - display_name: 第一层
      name: level_1
    - display_name: 第二层
      name: level_2
    - display_name: 第三层
      name: level_3
    tabs:
    - visible: false
      name: audits
    - visible: false
      name: notes
    searchable_columns:
    - name
    - slug
  updated_at: 2026-06-17 10:38:45.313157000 +00:00
- name: inquiry
  preferences:
    display_name: 询盘请求
  updated_at: 2026-06-22 02:23:42.299467000 +00:00
- name: product
  preferences:
    columns:
    - column_type: richtext
      display_name: 描述
      name: description
    - display_name: 主图
      reference:
        name: image_attachment
        display_name: Image attachment
        model_name: active_storage/attachment
        reference_type: has_one
        foreign_key: record_id
        primary_key: id
        options: {}
        polymorphic:
        virtual: false
      name: image_attachment
    - display_name: 标题
      name: title
    - display_name: 价格
      name: price
    - display_name: 更新时间
      name: updated_at
    - display_name: 创建时间
      name: created_at
    - display_name: 类别
      reference:
        name: category
        display_name: Category
        model_name: category
        reference_type: belongs_to
        foreign_key: category_id
        primary_key: id
        options: {}
        polymorphic:
        virtual: false
      name: category_id
    - display_name: 规格
      column_type: richtext
      name: specifications
    - access_type: hidden
      name: slug
    associations:
    - display_name: 多图
      name: images_attachments
    display_name: 商品列表
    tabs:
    - visible: false
      name: notes
    - visible: false
      name: audits
    searchable_columns:
    - title
    - sku
    scopes:
    - display_name: Kitchen Appliances
      name: kitchen_appliances
    - display_name: Beauty & Personal Care
      name: beauty_personal_care
  updated_at: 2026-06-26 11:34:52.362535000 +00:00
- name: user
  preferences:
    display_name: 用户
    visible: false
  updated_at: 2026-06-17 11:07:36.604127000 +00:00
configs:
- key: header.links
  value:
  - name: Reports
    link_type: reports
  - name: Forms
    link_type: forms
  updated_at: 2026-06-22 03:32:32.511529000 +00:00
- key: resources.category.scopes.order
  value:
  - level_1
  - level_2
  - level_3
  updated_at: 2026-06-17 09:57:07.977053000 +00:00
- key: resources.product.columns.order
  value:
  - id
  - category_id
  - image_attachment
  - title
  - sku
  - specifications
  - slug
  - price
  - description
  - updated_at
  - created_at
  updated_at: 2026-06-22 02:24:12.538675000 +00:00
- key: resources.product.scopes.order
  value:
  - kitchen_appliances
  - beauty_personal_care
  updated_at: 2026-06-26 02:59:04.752448000 +00:00
queries: []
dashboards: []
forms: []
alerts: []
api_configs:
- id: 1
  name: origin
  url: "/"
  preferences: {}
  description:
  updated_at: 2026-06-18 07:05:50.016152000 +00:00
